Add config to remove root ssh access and install fail2ban
learntouselinux/infra pull request #5
Opened 2019-10-30 01:36 UTC by objectsforheads

## Resolves
https://github.com/learntouselinux/learntouselinux/issues/30
https://github.com/learntouselinux/learntouselinux/issues/31

I wanted to solve https://github.com/learntouselinux/learntouselinux/issues/32 in this PR as well but it looked more complicated than what are essentially 2 one-liners. I can call this a PR a WIP and add that on but this can be merged as-is as well.

## Tests

1. Confirm that root cannot ssh in:
```
$ ssh root@157.245.172.49
root@157.245.172.49: Permission denied (publickey).
```

2. Confirm that fail2ban has been added:
```
$ sudo fail2ban-client version
0.10.2
```

2019-10-30 01:38 UTC, jerrywardlow commented on user-data.yaml
> +disable_root: true
This could use a newline to differentiate the logical blocks of configuration.

2019-10-30 14:02 UTC, yevgenybulochnik commented on user-data.yaml
> +disable_root: true
I was curious to see how cloud-init actually disables root ssh login. Apparently all it does is prepends the root user `/root/.ssh/authorization_keys` with `no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"NONE\" rather than the user \"root\".';echo;sleep 10"`. It appears `sshd_config` is left unchanged. 

While this makes sense for cloud-init, I would argue its a bit misleading for our purposes and using `sed` to change `sshd_config` settings maybe a better approach. How do you guys feel about this?

2019-10-30 17:22 UTC, toozej commented on user-data.yaml
> +disable_root: true
interesting, I didn't realize that's how it worked in cloud-init. While I like the cleanliness to the user-data of using the built-in directive, that's kind of a hackjob way of actually blocking root from logging in via SSH. I would rather go for a quick `sed` to change `/etc/ssh/sshd_config` to disable root SSH access properly

2019-11-05 22:53 UTC, jerrywardlow requested changes
Sounds like based on feedback we want to skip using `disable_root: true` and instead use the methods outlined in the original issue, specifically modifying `/etc/ssh/sshd_config` and removing keys from `/root/.ssh/authorized_keys`. While `disable_root: true` does prevent a user from logging in as `root` over SSH, the method by which it accomplishes this is pretty hacky and doesn't achieve one of the Criteria for Success noted in the issue: "No SSH keys are authorized for the user `root`". With the method implemented in the proposed change, keys are still present.

2019-11-13 04:56 UTC, jerrywardlow commented
Closing, dupe of #8

2019-11-13 04:56 UTC, closed without merging