Apache setup, app index file setup, terraform adjustments
learntouselinux/infra pull request #6
Opened 2019-10-31 04:28 UTC by yevgenybulochnik

Apologize in advance, this PR addresses multiple issues. It just made more sense for me to make some of these changes in the same PR. 
1. Alphabetized github ssh key imports
2. Adjusted `droplet_ip` output to give a key value mapping based on droplet index => ip4v_address
3. Install and configure apache2
4. use `git` to clone the app repo into `/tmp` and `cp` the index file into `/var/www/learntouselinux.com` 

NOTE: At this time I have not committed changes to `terraform.tfstate` once this PR is ready to merge I will create another commit for the new tfstate and create a PR to adjust the dns records 

## Resolves
learntouselinux/learntouselinux#25 
learntouselinux/learntouselinux#26 
learntouselinux/learntouselinux#32 
learntouselinux/learntouselinux#33 

## Tests
Droplet output
```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

droplet_ip = {
  "0" = "167.71.144.138"
}
```
Result of `curl 167.71.144.138`
```
Delete all other operating systems.
```

2019-10-31 17:36 UTC, jerrywardlow commented on outputs.tf
> +  # value = digitalocean_droplet.droplets.*.ipv4_address
Since this isn't backwards compatible to Terraform < 0.12.x let's make sure we document somewhere or let it be known that we're committing to the modern syntax and require everyone to be on 0.12.x+

2019-10-31 17:38 UTC, jerrywardlow commented on user-data.yaml
> +  - cp /tmp/app/index.html /var/www/learntouselinux.com
If we're pulling down the whole git repository why not put it somewhere persistent and symlink `index.html`?

2019-11-01 14:30 UTC, yevgenybulochnik commented on outputs.tf
> +  # value = digitalocean_droplet.droplets.*.ipv4_address
Added a comment to this specific output. I think once we decide on the readme for this repo and the meta repo we should include a comment on tf compatibility.

2019-11-01 14:32 UTC, yevgenybulochnik commented on user-data.yaml
> +  - cp /tmp/app/index.html /var/www/learntouselinux.com
Changed to clone into ltul user `~` and symlink to `/var/www/learntouselinux.com`

2019-11-04 18:29 UTC, jerrywardlow reviewed
Would love some brief code comments in `user-data.yaml`, otherwise this is solid 👍

2019-11-06 03:56 UTC, jerrywardlow requested changes
No periods on comments please!

2019-11-06 03:57 UTC, swhi3635 commented
![image](https://media1.tenor.com/images/64b35ffca1ac4f92e96fe9ab282e180f/tenor.gif?itemid=5876035)

2019-11-06 04:00 UTC, jerrywardlow submitted a review, later dismissed
:sunglasses:

2019-11-06 04:03 UTC, swhi3635 submitted a review, later dismissed

2019-11-06 04:14 UTC, jerrywardlow approved these changes
```
$ curl 157.245.169.240
Delete all other operating systems.
```
:heart_eyes:

2019-11-06 04:33 UTC, merged